Project_ShopOnline/Areas/Admin/Controllers/HomeAdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_ShopOnline.Areas.Admin.Controllers
{
    public class HomeAdminController : Controller
    {
        // GET: Admin/Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Admin/Admin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Admin/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Admin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Admin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Admin/Admin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Admin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/Admin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project_ShopOnline/Areas/Admin/Controllers/ProductController.cs
using PagedList;
using Project_ShopOnline.Models.DB;
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_ShopOnline.Areas.Admin.Controllers
{
    public class ProductController : Controller
    {
        // GET: Admin/Product
        public ActionResult Index()
        {
            return View(ShopOnlineDB.DanhSachSP());
        }

        // GET: Admin/Product/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Product/Create
        public ActionResult Create()
        {
            ViewBag.MaNhaSanXuat = new SelectList(NhaSanXuatDB.List(), "MaNhaSanXuat", "TenNhaSanXuat");
            ViewBag.MaLoaiSanPham = new SelectList(LoaiSanPhamDB.List(), "MaLoaiSanPham", "TenLoaiSanPham");
            return View();
        }

        // POST: Admin/Product/Create
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Create(SanPham sp)
        {
            try
            {
                var hpf = HttpContext.Request.Files[0];
                if (hpf.ContentLength > 0)
                {
                    string fileName = sp.MaSanPham;

                    string fullPathWithFileName = "~/Asset/images" + fileName + ".png";
                    hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                    sp.HinhChinh = sp.MaSanPham + ".png";
                }
                sp.LuotView = 0;
                sp.SoLuongDaBan = 0;

                // TODO: Add insert logic here
                ShopOnlineDB.CreateSP(sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Product/Edit/5
        public ActionResult Edit(String id)
        {
            ViewBag.MaNhaSanXuat = new SelectList(NhaSanXuatDB.List(), "MaNhaSanXuat", "TenNhaSanXuat",ShopOnlineDB.ChiTiet(id).MaNhaSanXuat);
            ViewBag.MaLoaiSanPham = new SelectList(LoaiSanPhamDB.List(), "MaLoaiSanPham", "TenLoaiSanPham", ShopOnlineDB.ChiTiet(id).MaLoaiSanPham);
            return View(ShopOnlineDB.ChiTiet(id));
        }

        // POST: Admin/Product/Edit/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(String id, SanPham sp)
        {
            try
            {
                //var hpf = HttpContext.Request.Files[0];
                //if (hpf.ContentLength > 0)
                //{
                //    string fileName = sp.MaSanPham;

                //    string fullPathWithFileName = "~/Asset/images" + fileName + ".png";
                //    hpf.SaveAs(Server.MapPath(fullPathWithFileName));
                //    sp.HinhChinh = sp.MaSanPham + ".png";
                //}
                //if(sp.SoLuongDaBan > 10000)
                //{
                //    sp.SoLuongDaBan = 0;
                //}

                //if(sp.LuotView > 10000)
                //{
                //    sp.LuotView = 0;
                //}
                ShopOnlineDB.UpdateSP(id, sp);
                // TODO: Add insert logic here
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        // GET: Admin/Product/Lock/5
        public ActionResult Lock(String id)

        {
            ViewBag.MaNhaSanXuat = new SelectList(NhaSanXuatDB.List(), "MaNhaSanXuat", "TenNhaSanXuat", ShopOnlineDB.ChiTiet(id).MaNhaSanXuat);
            ViewBag.MaLoaiSanPham = new SelectList(LoaiSanPhamDB.List(), "MaLoaiSanPham", "TenLoaiSanPham", ShopOnlineDB.ChiTiet(id).MaLoaiSanPham);
            return View(ShopOnlineDB.ChiTiet(id));
        }

        // POST: Admin/Product/Lock/5
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Lock(String id, SanPham sp)
        {
            try
            {
                // TODO: Add delete logic here
                sp.TinhTrang = "1";
                ShopOnlineDB.UpdateSP(id, sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Product/Delete/5
        public ActionResult Delete(String id)
        {
            return View(ShopOnlineDB.ChiTiet(id));
        }

        // POST: Admin/Product/Delete/5
        [HttpPost]
        public ActionResult Delete(String id, SanPham sp) 
        {
            try
            {
                // TODO: Add delete logic here
                sp.TinhTrang = "1";
                ShopOnlineDB.UpdateSP(id, sp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project_ShopOnline/Areas/Admin/Controllers/ProductManufacturerController.cs
using Project_ShopOnline.Models.DB;
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_ShopOnline.Areas.Admin.Controllers
{
    public class ProductManufacturerController : Controller
    {
        // GET: Admin/ProductManufacturer
        public ActionResult Index()
        {
            var ds = NhaSanXuatDB.ListAdmin();
            return View(ds);
        }

        // GET: Admin/ProductManufacturer/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/ProductManufacturer/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ProductManufacturer/Create
        [HttpPost]
        public ActionResult Create(NhaSanXuat nsx)
        {
            try
            {
                // TODO: Add insert logic here
                NhaSanXuatDB.CreateNSX(nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/ProductManufacturer/Edit/5
        public ActionResult Edit(String id)
        {
            return View(NhaSanXuatDB.ChiTietAdmin(id));
        }

        // POST: Admin/ProductManufacturer/Edit/5
        [HttpPost]
        public ActionResult Edit(String id, NhaSanXuat nsx)
        {
            try
            {
                // TODO: Add update logic here
                NhaSanXuatDB.UpdateNSX(id,nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //-----Khoa NSX------
        public ActionResult Lock(String id)
        {
            return View(NhaSanXuatDB.ChiTietAdmin(id));
        }


        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/ProductManufacturer/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/ProductManufacturer/Delete/5
        [HttpPost]
        public ActionResult Lock(String id, NhaSanXuat nsx)
        {
            try
            {
                // TODO: Add delete logic here
                nsx.TinhTrang = "1";
                NhaSanXuatDB.UpdateNSX(id, nsx);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project_ShopOnline/Areas/Admin/Controllers/ProductTypeController.cs
using Project_ShopOnline.Models.DB;
using ShopOnlineConnection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_ShopOnline.Areas.Admin.Controllers
{
    public class ProductTypeController : Controller
    {
        // GET: Admin/ProductType
        public ActionResult Index()
        {
            var db = LoaiSanPhamDB.ListAdmin();
            return View(db);
        }

        // GET: Admin/ProductType/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/ProductType/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/ProductType/Create
        [HttpPost]
        public ActionResult Create(LoaiSanPham lsp)
        {
            try
            {
                // TODO: Add insert logic here
                LoaiSanPhamDB.CreateLSP(lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/ProductType/Edit/5
        public ActionResult Edit(String id)
        {
            //load db theo id
            var db = LoaiSanPhamDB.ChiTietAdmin(id);
            return View(db);
        }

        // POST: Admin/ProductType/Edit/5
        [HttpPost]
        public ActionResult Edit(String id, LoaiSanPham lsp)
        {
            try
            {
                // TODO: Add update logic here
                LoaiSanPhamDB.UpdateLSP(id, lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        //------LOCK-----

        // GET: Admin/ProductType/Lock/5
        public ActionResult Lock(String id)
        {
            var db = LoaiSanPhamDB.ChiTietAdmin(id);
            return View(db);
        }

        // POST: Admin/ProductType/Lock/5
        [HttpPost]
        public ActionResult Lock(String id, LoaiSanPham lsp)
        {
            try
            {
                // TODO: Add delete logic here
                lsp.TinhTrang = "1";
                LoaiSanPhamDB.UpdateLSP(id, lsp);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }





        // GET: Admin/ProductType/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Admin/ProductType/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project_ShopOnline/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Dashboard - SB Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet" />
    <link href="~/Areas/AssetsAdmin/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="@Url.Action("Index", "HomeAdmin")">Admin</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="#!">Settings</a></li>
                    <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                    <li><hr class="dropdown-divider" /></li>
                    <li><a class="dropdown-item" href="#!">Logout</a></li>
                </ul>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("Index","HomeAdmin")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>
                        @*<div class="sb-sidenav-menu-heading">Interface</div>*@
                        <a class="nav-link collapsed" href="@Url.Action("Index","ProductManufacturer")" @*data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts"*@>
                            <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                            Quản lý Nhà Sản Xuất
                        </a>

                        @*<div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="layout-static.html">Static Navigation</a>
                                <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                            </nav>
                        </div>*@
                        <a class="nav-link collapsed" href="@Url.Action("Index","ProductType")" @*data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages"*@>
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Quản lý Loại sản phẫm
                            @*<div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>*@
                        </a>
                        @*<div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                            <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                                    Authentication
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="login.html">Login</a>
                                        <a class="nav-link" href="register.html">Register</a>
                                        <a class="nav-link" href="password.html">Forgot Password</a>
                                    </nav>  
                                </div>
                                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                    Error
                                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                </a>
                                <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                                    <nav class="sb-sidenav-menu-nested nav">
                                        <a class="nav-link" href="401.html">401 Page</a>
                                        <a class="nav-link" href="404.html">404 Page</a>
                                        <a class="nav-link" href="500.html">500 Page</a>
                                    </nav>
                                </div>
                            </nav>
                        </div>*@
                        @*<div class="sb-sidenav-menu-heading">Addons</div>*@
                        <a class="nav-link" href="@Url.Action("Index","Product")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Sản phẫm
                        </a>
                        @*<a class="nav-link" href="tables.html">
                            <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                            Tables
                        </a>*@
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Start Bootstrap
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/AssetsAdmin/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/AssetsAdmin/assets/demo/chart-area-demo.js"></script>
    <script src="~/Areas/AssetsAdmin/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
    <script src="~/Areas/AssetsAdmin/js/datatables-simple-demo.js"></script>
</body>
</html>