Project_ShopOnline/Controllers/GioHangController.cs
using Project_ShopOnline.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_ShopOnline.Controllers
{
    
    public class GioHangController : Controller
    {
        // GET: GioHang
        public ActionResult Index()
        {
            ViewBag.TongTien = GioHangDB.TongTien();
            return View(GioHangDB.DanhSach());
        }

        [HttpPost]
        public ActionResult Them(string masanpham, string tensanpham, int gia, int soluong)
        {
            try
            {
                GioHangDB.Them(masanpham, tensanpham, gia, soluong);
                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("../Shop/Index");
            }
        }

        [HttpPost]
        public ActionResult CapNhat(string masanpham, string tensanpham, int gia, int soluong)
        {
            try
            {
                GioHangDB.CapNhat(masanpham, tensanpham, gia, soluong);
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }
        [HttpGet]
        public ActionResult Xoa(string masanpham)
        {
            try
            {
                GioHangDB.Xoa(masanpham);
                return RedirectToAction("index");
            }
            catch
            {
                return RedirectToAction("../Shop/index");
            }

        }

        // GET: GioHang/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: GioHang/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GioHang/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GioHang/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: GioHang/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: GioHang/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: GioHang/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project_ShopOnline/Controllers/ShopController.cs
using PagedList;
using Project_ShopOnline.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Project_ShopOnline.Controllers
{
    public class ShopController : Controller
    {

        // GET: Shop
        public ActionResult Index(int page = 1, int pagesize = 6)
        {
            var db = ShopOnlineDB.DanhSach().ToPagedList(page,pagesize);
            return View(db);
        }

        // GET: Shop/Details/5
        public ActionResult Details(String id)
        {
            var db = ShopOnlineDB.ChiTiet(id);
            return View(db);
        }

        // GET: Shop/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Shop/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Shop/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Shop/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Project_ShopOnline/Views/GioHang/Index.cshtml
@model IEnumerable<ShopOnlineConnection.GioHang>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}
    <!--//////////////////////////////////////////////////-->
    <!--///////////////////Cart Page//////////////////////-->
    <!--//////////////////////////////////////////////////-->
<div id="page-content" class="single-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a></li>
                    <li><a href="cart.html">Cart</a></li>
                </ul>
            </div>
        </div>

        @foreach (var item in Model)
        {
            <div class="row">
                <div class="product well">
                    <div class="col-md-3">
                        <div class="image"> 
                            <img src="images/galaxy-note.jpg" />
                        </div>
                    </div>
                    <div class="col-md-9">
                        <div class="caption">
                            @using (Html.BeginForm("CapNhat", "GioHang", FormMethod.Post))
                            {
                                <input type="hidden" name="masanpham" value="@item.MaSanPham" />
                                <input type="hidden" name="tensanpham" value="@item.TenSanPham" />
                                <input type="hidden" name="gia" value="@item.Gia" />
                                @Html.Partial("_GioHang", Project_ShopOnline.Models.DB.ShopOnlineDB.ChiTiet(item.MaSanPham.ToString()))
                                <label>Số lượng : </label> <input class="form-inline quantity" style="width: 110px" min="1" max="1000" type="number" value="@item.SoLuong" name="soluong"><input type="submit" class="btn btn-2 " value="Update" /> <br />
                                <span>Tổng Tiền : @item.TongTien đ</span>
                                <hr>
                            }
                            <a href="@Url.Action("Xoa","GioHang",new { masanpham= item.MaSanPham})" class="btn btn-default pull-right">REMOVE</a>
                        </div>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        }



        @*Quay về trang sản phẩm*@
        <div class="row">
            <div class="col-md-4 col-md-offset-8 ">
                <center><a href="@Url.Action("index","Shop")" class="btn btn-1">Continue To Shopping</a></center>
            </div>
        </div>

        @*Tính tiền*@
        <div class="row">
            <div class="pricedetails">
                <div class="col-md-4 col-md-offset-8">
                    <table>
                        <h6>Tính tiền : </h6>
                        <tr>
                            <td>Tổng</td>
                            <td>@ViewBag.TongTien đ</td>
                        </tr>

                        <tr>
                            <td>Giảm giá : </td>
                            <td>0</td>
                        </tr>
                        <tr style="border-top: 1px solid #333">
                            <td><h5>THÀNH TIỀN</h5></td>
                            <td>@ViewBag.TongTien đ</td>
                        </tr>
                    </table>
                    <center><a href="@Url.Action("index","ThanhToan")" class="btn btn-1">Checkout</a></center>
                </div>
            </div>
        </div>
    </div>
</div>